package com.lanou3g.lesson.model.entity.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "RECOMMEND_ENTITY".
 */
public class RecommendEntity {

    private Long id;
    private String title;
    private String tag;
    private String share_title;
    private String description;
    private String share;
    private String thumb;
    private String published_at;
    private String url;
    private String channel;
    private String label;
    private String label_color;
    private String scheme;
    private Integer comments_total;

    public RecommendEntity() {
    }

    public RecommendEntity(Long id) {
        this.id = id;
    }

    public RecommendEntity(Long id, String title, String tag, String share_title, String description, String share, String thumb, String published_at, String url, String channel, String label, String label_color, String scheme, Integer comments_total) {
        this.id = id;
        this.title = title;
        this.tag = tag;
        this.share_title = share_title;
        this.description = description;
        this.share = share;
        this.thumb = thumb;
        this.published_at = published_at;
        this.url = url;
        this.channel = channel;
        this.label = label;
        this.label_color = label_color;
        this.scheme = scheme;
        this.comments_total = comments_total;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getShare_title() {
        return share_title;
    }

    public void setShare_title(String share_title) {
        this.share_title = share_title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getShare() {
        return share;
    }

    public void setShare(String share) {
        this.share = share;
    }

    public String getThumb() {
        return thumb;
    }

    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    public String getPublished_at() {
        return published_at;
    }

    public void setPublished_at(String published_at) {
        this.published_at = published_at;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getChannel() {
        return channel;
    }

    public void setChannel(String channel) {
        this.channel = channel;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getLabel_color() {
        return label_color;
    }

    public void setLabel_color(String label_color) {
        this.label_color = label_color;
    }

    public String getScheme() {
        return scheme;
    }

    public void setScheme(String scheme) {
        this.scheme = scheme;
    }

    public Integer getComments_total() {
        return comments_total;
    }

    public void setComments_total(Integer comments_total) {
        this.comments_total = comments_total;
    }

}
