package com.lanou3g.lesson.test;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lanou3g.lesson.test.DaoTest;

import com.lanou3g.lesson.test.DaoTestDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig daoTestDaoConfig;

    private final DaoTestDao daoTestDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        daoTestDaoConfig = daoConfigMap.get(DaoTestDao.class).clone();
        daoTestDaoConfig.initIdentityScope(type);

        daoTestDao = new DaoTestDao(daoTestDaoConfig, this);

        registerDao(DaoTest.class, daoTestDao);
    }
    
    public void clear() {
        daoTestDaoConfig.getIdentityScope().clear();
    }

    public DaoTestDao getDaoTestDao() {
        return daoTestDao;
    }

}
