package com.lanou3g.lesson.test;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DAO_TEST".
 */
public class DaoTest {

    private Long _id;

    public DaoTest() {
    }

    public DaoTest(Long _id) {
        this._id = _id;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

}
